# Generated by Django 4.1.3 on 2022-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_rename_shop_name_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
