# Generated by Django 4.1.7 on 2023-03-07 18:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_category_shop_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=13), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
