# Generated by Django 4.1.7 on 2023-03-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_product_ean_product_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
