# Generated by Django 4.1.7 on 2023-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_alter_price_options_alter_product_shop_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='search_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
